# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpdatinghomeregistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_updatinghomeregistration(self):
    self.driver.get("http://localhost:8010/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(3) > .nav-link").click()
    self.driver.find_element(By.ID, "exampleInputEmail1").click()
    self.driver.find_element(By.ID, "exampleInputEmail1").send_keys("riya_05")
    self.driver.find_element(By.ID, "exampleInputPassword1").click()
    self.driver.find_element(By.ID, "exampleInputPassword1").send_keys("1234")
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.CSS_SELECTOR, "b").click()
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    self.driver.find_element(By.ID, "rent").click()
    self.driver.find_element(By.ID, "rent").send_keys("9000")
    self.driver.find_element(By.ID, "sale").click()
    self.driver.find_element(By.ID, "sale").send_keys("40000")
    self.driver.find_element(By.ID, "deposit").click()
    self.driver.find_element(By.ID, "deposit").send_keys("20000")
    self.driver.find_element(By.ID, "other").click()
    self.driver.find_element(By.ID, "other").send_keys("including water and electricity bill")
    self.driver.find_element(By.NAME, "register_individuals").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, "b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-uppercase > .nav-item:nth-child(2) > .nav-link").click()
  
