# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://localhost:8010/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item > .js-scroll-trigger").click()
    self.driver.find_element(By.ID, "keywords").click()
    self.driver.find_element(By.ID, "keywords").send_keys("1 bhk")
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.ID, "location").click()
    self.driver.find_element(By.ID, "location").send_keys("Ranchi")
    self.driver.find_element(By.NAME, "search").click()
  
