# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIndividualhomeregistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_individualhomeregistration(self):
    self.driver.get("http://localhost:8010/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(3) > .nav-link").click()
    self.driver.find_element(By.ID, "exampleInputEmail1").click()
    self.driver.find_element(By.ID, "exampleInputEmail1").send_keys("riya_05")
    self.driver.find_element(By.ID, "exampleInputPassword1").click()
    self.driver.find_element(By.ID, "exampleInputPassword1").send_keys("1234")
    self.driver.find_element(By.NAME, "login").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "fullname").click()
    self.driver.find_element(By.ID, "fullname").send_keys("Riya Sagar")
    self.driver.find_element(By.ID, "mobile").click()
    self.driver.find_element(By.ID, "mobile").send_keys("1234567891")
    self.driver.find_element(By.ID, "alternat_mobile").click()
    self.driver.find_element(By.ID, "alternat_mobile").send_keys("5432167891")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("riyasagar121@gmail.com")
    self.driver.find_element(By.ID, "plot_number").click()
    self.driver.find_element(By.ID, "plot_number").send_keys("#12")
    self.driver.find_element(By.ID, "rooms").click()
    self.driver.find_element(By.ID, "rooms").send_keys("2 bhk")
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.ID, "country").send_keys("India")
    self.driver.find_element(By.ID, "state").click()
    self.driver.find_element(By.ID, "state").send_keys("Jharkhand")
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "city").send_keys("Ranchi")
    self.driver.find_element(By.ID, "rent").click()
    self.driver.find_element(By.ID, "rent").send_keys("15000")
    self.driver.find_element(By.ID, "sale").click()
    self.driver.find_element(By.ID, "sale").send_keys("900000")
    self.driver.find_element(By.ID, "deposit").click()
    self.driver.find_element(By.ID, "deposit").send_keys("150000")
    self.driver.find_element(By.ID, "accommodation").click()
    self.driver.find_element(By.ID, "accommodation").send_keys("full furnished")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("maximum 6 members")
    self.driver.find_element(By.ID, "landmark").click()
    self.driver.find_element(By.ID, "landmark").send_keys("lalpur chowk")
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("near Dlx mall")
    self.driver.find_element(By.NAME, "register_individuals").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
  
